package Views;

import javax.swing.table.DefaultTableModel;
import Controllers.ParkingController;
import Controllers.TestingController;
import Models.Floor;
import Models.Vehicle;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author SAK
 */
public class ParkingView extends javax.swing.JFrame {

    private ParkingController controller = new ParkingController();
    private Date newTimeOut;
    private boolean rdo_tblShowVehiclesAllOn = true;

    public ParkingView() {;
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txt_info.setEditable(false);
        DefaultTableModel tableModel = (DefaultTableModel) tbl_vehicle.getModel();
        tbl_vehicle.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableModel.setRowCount(0);
        rdo_tblShowVehiclesAll.setSelected(true);

        displayFloorTable(controller.getAllFloors());
        displayFloorCombo(controller.getAllFloors());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_checkin = new javax.swing.JButton();
        cbo_floor = new javax.swing.JComboBox<>();
        btn_checkout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_floor = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vehicle = new javax.swing.JTable();
        txt_vehicleIdIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_info = new javax.swing.JTextArea();
        btn_confirmPayment = new javax.swing.JButton();
        btn_addhour = new javax.swing.JButton();
        rdo_tblShowVehiclesAll = new javax.swing.JRadioButton();
        btn_genIDin = new javax.swing.JButton();
        btn_genIDout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_vehicleIdOut = new javax.swing.JTextField();
        txt_totalMoney = new javax.swing.JLabel();
        txt_totalVehiclesStay = new javax.swing.JLabel();
        txt_totalVehiclesLeft = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_mall = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Floor:");

        btn_checkin.setBackground(new java.awt.Color(0, 0, 204));
        btn_checkin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_checkin.setForeground(new java.awt.Color(255, 255, 255));
        btn_checkin.setText("Check In");
        btn_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkinActionPerformed(evt);
            }
        });

        cbo_floor.setBackground(new java.awt.Color(255, 255, 255));
        cbo_floor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbo_floor.setForeground(new java.awt.Color(0, 0, 0));
        cbo_floor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FG", "F1", "F2", "F3", "F4" }));
        cbo_floor.setToolTipText("");
        cbo_floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_floorActionPerformed(evt);
            }
        });

        btn_checkout.setBackground(new java.awt.Color(204, 0, 0));
        btn_checkout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_checkout.setForeground(new java.awt.Color(255, 255, 255));
        btn_checkout.setText("Check Out");
        btn_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkoutActionPerformed(evt);
            }
        });

        tbl_floor.setBackground(new java.awt.Color(255, 255, 255));
        tbl_floor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_floor.setForeground(new java.awt.Color(0, 0, 0));
        tbl_floor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"F3",  new Integer(3),  new Integer(10)},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Floor ID", "Vehicles", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_floor.setEnabled(false);
        tbl_floor.setRowHeight(40);
        tbl_floor.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_floor.setShowGrid(true);
        jScrollPane2.setViewportView(tbl_floor);
        if (tbl_floor.getColumnModel().getColumnCount() > 0) {
            tbl_floor.getColumnModel().getColumn(0).setResizable(false);
            tbl_floor.getColumnModel().getColumn(1).setResizable(false);
            tbl_floor.getColumnModel().getColumn(2).setResizable(false);
        }

        tbl_vehicle.setBackground(new java.awt.Color(255, 255, 255));
        tbl_vehicle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_vehicle.setForeground(new java.awt.Color(0, 0, 0));
        tbl_vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Floor", "Time In", "Time  Out", "Duration", "Paid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_vehicle.setRowHeight(30);
        tbl_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_vehicleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_vehicle);
        if (tbl_vehicle.getColumnModel().getColumnCount() > 0) {
            tbl_vehicle.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_vehicle.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_vehicle.getColumnModel().getColumn(4).setPreferredWidth(20);
            tbl_vehicle.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        txt_vehicleIdIn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_vehicleIdIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vehicleIdInActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Vehicles ID:");

        txt_info.setBackground(new java.awt.Color(255, 255, 255));
        txt_info.setColumns(20);
        txt_info.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_info.setForeground(new java.awt.Color(0, 0, 0));
        txt_info.setRows(5);
        jScrollPane3.setViewportView(txt_info);

        btn_confirmPayment.setBackground(new java.awt.Color(0, 153, 0));
        btn_confirmPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_confirmPayment.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmPayment.setText("Confirm Payment");
        btn_confirmPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmPaymentActionPerformed(evt);
            }
        });

        btn_addhour.setBackground(new java.awt.Color(255, 255, 255));
        btn_addhour.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_addhour.setForeground(new java.awt.Color(153, 153, 153));
        btn_addhour.setText("+1h");
        btn_addhour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addhourActionPerformed(evt);
            }
        });

        rdo_tblShowVehiclesAll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_tblShowVehiclesAll.setForeground(new java.awt.Color(0, 0, 0));
        rdo_tblShowVehiclesAll.setText("Show All Vehicles");
        rdo_tblShowVehiclesAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_tblShowVehiclesAllActionPerformed(evt);
            }
        });

        btn_genIDin.setBackground(new java.awt.Color(255, 255, 255));
        btn_genIDin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_genIDin.setForeground(new java.awt.Color(153, 153, 153));
        btn_genIDin.setText("Scan In Plate ID");
        btn_genIDin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genIDinActionPerformed(evt);
            }
        });

        btn_genIDout.setBackground(new java.awt.Color(255, 255, 255));
        btn_genIDout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_genIDout.setForeground(new java.awt.Color(153, 153, 153));
        btn_genIDout.setText("Scan Out Plate ID");
        btn_genIDout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genIDoutActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vehicles ID:");

        txt_vehicleIdOut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_vehicleIdOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vehicleIdOutActionPerformed(evt);
            }
        });

        txt_totalMoney.setBackground(new java.awt.Color(255, 255, 255));
        txt_totalMoney.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_totalMoney.setForeground(new java.awt.Color(204, 0, 204));
        txt_totalMoney.setText("Total Money: 0.0 riel");

        txt_totalVehiclesStay.setBackground(new java.awt.Color(255, 255, 255));
        txt_totalVehiclesStay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_totalVehiclesStay.setForeground(new java.awt.Color(204, 0, 204));
        txt_totalVehiclesStay.setText("Total Vehicles Stay: 0");

        txt_totalVehiclesLeft.setBackground(new java.awt.Color(255, 255, 255));
        txt_totalVehiclesLeft.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_totalVehiclesLeft.setForeground(new java.awt.Color(204, 0, 204));
        txt_totalVehiclesLeft.setText("Total Vehicles Left: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(btn_confirmPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_checkout, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_vehicleIdIn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txt_vehicleIdOut))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_totalMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(227, 227, 227))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_totalVehiclesStay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btn_addhour))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_totalVehiclesLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(272, 272, 272)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_genIDout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_genIDin, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(701, 701, 701))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdo_tblShowVehiclesAll))
                        .addGap(732, 732, 732))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_floor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vehicleIdIn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vehicleIdOut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirmPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_genIDin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_genIDout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_addhour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_totalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_totalVehiclesStay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_totalVehiclesLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(rdo_tblShowVehiclesAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_mall.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_mall.setForeground(new java.awt.Color(255, 51, 255));
        txt_mall.setText("BEON Mall Parking");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txt_mall, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_mall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayFloorTable(LinkedHashMap<Floor, Integer> getAllFloors) {

        DefaultTableModel tableModel = (DefaultTableModel) tbl_floor.getModel();
        tableModel.setRowCount(0);

        LinkedHashMap<Floor, Integer> floors = getAllFloors;
        for (Floor floor : floors.keySet()) {
            int vehicleCount = floors.get(floor);
            Object[] rowData = {floor.getFloorId(), vehicleCount, floor.getCapacity()};
            tableModel.addRow(rowData);
        }
    }

    private void displayFloorCombo(LinkedHashMap<Floor, Integer> getAllFloors) {
        cbo_floor.removeAllItems();

        LinkedHashMap<Floor, Integer> floors = getAllFloors;
        for (Floor floor : floors.keySet()) {
            cbo_floor.addItem(floor.getFloorId());
        }
    }

    private void displayVehicleTable(List<Vehicle> getAllVehicles) {
        DefaultTableModel tableModel = (DefaultTableModel) tbl_vehicle.getModel();
        tableModel.setRowCount(0);

        SimpleDateFormat formatter = new SimpleDateFormat("H:m:s a dd/MM/yy");
        List<Vehicle> vehicles = getAllVehicles;
        for (Vehicle vehicle : vehicles) {

            if (rdo_tblShowVehiclesAllOn) {
                Object[] rowData = {
                    vehicle.getVehicleId(),
                    vehicle.getFloor().getFloorId(),
                    formatter.format(vehicle.getTimeIn()),
                    vehicle.getTimeOut() != null ? formatter.format(vehicle.getTimeOut()) : "",
                    controller.CalculateDuration(vehicle.getTimeIn(), vehicle.getTimeOut()),
                    controller.CalculateCost(vehicle.getTimeIn(), vehicle.getTimeOut())

                };
                tableModel.addRow(rowData);

            } else if (vehicle.getTimeOut() == null) {
                Object[] rowData = {
                    vehicle.getVehicleId(),
                    vehicle.getFloor().getFloorId(),
                    formatter.format(vehicle.getTimeIn()),
                    vehicle.getTimeOut() != null ? formatter.format(vehicle.getTimeOut()) : "",
                    controller.CalculateDuration(vehicle.getTimeIn(), vehicle.getTimeOut()),
                    controller.CalculateCost(vehicle.getTimeIn(), vehicle.getTimeOut())
                };
                tableModel.addRow(rowData);
            }
        }
        txt_totalMoney.setText("Total Money: " + totalMoney(getAllVehicles));
        txt_totalVehiclesStay.setText("Total Vehicles Stay: " + totalVehiclesStayCount(getAllVehicles));
        txt_totalVehiclesLeft.setText("Total Vehicles Left: " + totalVehiclesLeftCount(getAllVehicles));
    }

    
    private String totalMoney(List<Vehicle> getAllVehicles) {
        double total = 0;
        List<Vehicle> vehicles = getAllVehicles;
        for (Vehicle vehicle : vehicles) {
            if (vehicle.getTimeOut() != null) {
                total = total + controller.CalculateCostDouble(vehicle.getTimeIn(), vehicle.getTimeOut());
            }
        }
        return total + " riel";
    }

    private int totalVehiclesStayCount(List<Vehicle> getAllVehicles) {
        int total = 0;
        List<Vehicle> vehicles = getAllVehicles;
        for (Vehicle vehicle : vehicles) {
            if (vehicle.getTimeOut() == null) {
                total++;
            }
        }
        return total;
    }
    
    private int totalVehiclesLeftCount(List<Vehicle> getAllVehicles) {
        int total = 0;
        List<Vehicle> vehicles = getAllVehicles;
        for (Vehicle vehicle : vehicles) {
            if (vehicle.getTimeOut() != null) {
                total++;
            }
        }
        return total;
    }

    private void checkInClick(String txt_vehicleId) {
        if (txt_vehicleId.isEmpty()) {
            String message = "\" Error 69 \"\n" + "input a vehicle ID PLEASE \n";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String selectedVehicleId = txt_vehicleId;
                newTimeOut = new Date();
                txt_info.setText(controller.CheckOut(selectedVehicleId, newTimeOut));
                h = 0;

            } catch (Exception e) {
                String message = "\" Error 69 \"\n your input vehicle ID:'" + txt_vehicleId + "' is not found \n";
                JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void checkOutClick(String txt_vehicleId) {
        if (txt_vehicleId.isEmpty()) {
            String message = "\" Error 69 \"\n" + "input a vehicle ID PLEASE \n";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                controller.CheckIn((String) cbo_floor.getSelectedItem(), txt_vehicleIdIn.getText());
                displayFloorTable(controller.getAllFloors());
                displayVehicleTable(controller.getAllVehicles());
                txt_info.setText(txt_vehicleId + " Successfully In!");
                txt_vehicleIdIn.setText("");

            } catch (Exception e) {
                String message = "\" Error 69 \"\n your input vehicle ID:'" + txt_vehicleId + "' is not found \n";
                JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btn_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkinActionPerformed
        checkOutClick(txt_vehicleIdIn.getText());
    }//GEN-LAST:event_btn_checkinActionPerformed

    int h = 0;

    private void btn_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkoutActionPerformed
        checkInClick(txt_vehicleIdOut.getText());
    }//GEN-LAST:event_btn_checkoutActionPerformed

    private void cbo_floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_floorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbo_floorActionPerformed

    private void btn_confirmPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmPaymentActionPerformed
        // TODO add your handling code here:
        if (newTimeOut != null) {
            controller.ConfirmPayment(txt_vehicleIdOut.getText(), newTimeOut);

            displayFloorTable(controller.getAllFloors());
            displayVehicleTable(controller.getAllVehicles());
            txt_info.setText("Paid, SAY Thank you to Our Customers, BOYS!");
            newTimeOut = null;
            txt_vehicleIdOut.setText("");
        } else {
            String message = "\" Error 69 \"\n" + "select a vehicle PLEASE";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmPaymentActionPerformed


    private void btn_addhourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addhourActionPerformed
        // TODO add your handling code here:
        try {
            String selectedVehicleId = txt_vehicleIdOut.getText();
            newTimeOut = new Date();
            h += 1;
            newTimeOut = new Date(newTimeOut.getTime() + (h * 60 * 60 * 1000));
            txt_info.setText(controller.CheckOut(selectedVehicleId, newTimeOut));

        } catch (Exception e) {
            String message = "\" Error 69 \"\n"
                    + "select a vehicle PLEASE";
            JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_addhourActionPerformed

    private void tbl_vehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_vehicleMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tbl_vehicle.getModel();

        if (tbl_vehicle.getSelectedRowCount() == 1) {
            try {

                String selectedVehicleId = tbl_vehicle.getModel().getValueAt(tbl_vehicle.getSelectedRow(), 0).toString();
                txt_vehicleIdOut.setText(selectedVehicleId);
                newTimeOut = new Date();
                txt_info.setText(controller.CheckOut(selectedVehicleId, newTimeOut));
                h = 0;

            } catch (Exception e) {
                String message = "\" Error 69 \"\n";
                JOptionPane.showMessageDialog(new JFrame(), message, "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tbl_vehicleMouseClicked

    private void rdo_tblShowVehiclesAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_tblShowVehiclesAllActionPerformed
        // TODO add your handling code here:
        if (rdo_tblShowVehiclesAll.isSelected()) {
            rdo_tblShowVehiclesAllOn = true;
            displayVehicleTable(controller.getAllVehicles());

        } else {
            rdo_tblShowVehiclesAllOn = false;
            displayVehicleTable(controller.getAllVehicles());
        }

    }//GEN-LAST:event_rdo_tblShowVehiclesAllActionPerformed

    private void btn_genIDinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genIDinActionPerformed
        // TODO add your handling code here:
        txt_vehicleIdIn.setText(TestingController.generatePlateId());
    }//GEN-LAST:event_btn_genIDinActionPerformed

    public Vehicle getRandomVehicleWithoutTimeout(List<Vehicle> vehicles) {
        List<Vehicle> filteredVehicles = new ArrayList<>();
        for (Vehicle vehicle : vehicles) {
            if (vehicle.getTimeOut() == null) {
                filteredVehicles.add(vehicle);
            }
        }

        if (!filteredVehicles.isEmpty()) { // Check if any vehicles without timeout exist
            Random random = new Random();
            int index = random.nextInt(filteredVehicles.size());
            return filteredVehicles.get(index);
        } else {
            return null; // Return null if no vehicles without timeout are found
        }
    }

    private void btn_genIDoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genIDoutActionPerformed
        // TODO add your handling code here:
        List<Vehicle> allVehicles = controller.getAllVehicles();
        Vehicle randomAvailableVehicle = getRandomVehicleWithoutTimeout(allVehicles);

        if (randomAvailableVehicle != null) {
            txt_vehicleIdOut.setText(randomAvailableVehicle.getVehicleId());
            checkInClick(txt_vehicleIdOut.getText());
        }
    }//GEN-LAST:event_btn_genIDoutActionPerformed

    private void txt_vehicleIdInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vehicleIdInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vehicleIdInActionPerformed

    private void txt_vehicleIdOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vehicleIdOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vehicleIdOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addhour;
    private javax.swing.JButton btn_checkin;
    private javax.swing.JButton btn_checkout;
    private javax.swing.JButton btn_confirmPayment;
    private javax.swing.JButton btn_genIDin;
    private javax.swing.JButton btn_genIDout;
    private javax.swing.JComboBox<String> cbo_floor;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdo_tblShowVehiclesAll;
    private javax.swing.JTable tbl_floor;
    private javax.swing.JTable tbl_vehicle;
    private javax.swing.JTextArea txt_info;
    private javax.swing.JLabel txt_mall;
    private javax.swing.JLabel txt_totalMoney;
    private javax.swing.JLabel txt_totalVehiclesLeft;
    private javax.swing.JLabel txt_totalVehiclesStay;
    private javax.swing.JTextField txt_vehicleIdIn;
    private javax.swing.JTextField txt_vehicleIdOut;
    // End of variables declaration//GEN-END:variables

}
